'use strict';


const ActionNames = {
    CONVERSATIONS_LOAD_NEXT_PAGE: 'CONVERSATIONS_LOAD_NEXT_PAGE',
    CONVERSATIONS_LOADED: 'CONVERSATIONS_LOADED',
    CONVERSATIONS_NO_MORE: 'CONVERSATIONS_NO_MORE',
};

export default ActionNames;