'use strict';


export const ActionNames = {
    USER_LOGIN: 'USER_LOGIN',
    USER_SIGN_UP: 'USER_SIGN_UP',
    USER_EDIT: 'USER_EDIT',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_AUTHENTICATE: 'USER_AUTHENTICATE',
    USER_AUTHENTICATED: 'USER_AUTHENTICATED',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    USER_LOGIN_SUCCEEDED: 'USER_LOGIN_SUCCEEDED',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
};

export default ActionNames;